#!/bin/bash

#
# VitalPBX Asterisk Wallboard - Installation Script
#
# Usage: ./install.sh
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print banner
echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║        VitalPBX Asterisk Wallboard Installer               ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed.${NC}"
    echo "Please install Docker first: https://docs.docker.com/engine/install/"
    exit 1
fi

# Check if Docker Compose is installed
if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose is not installed.${NC}"
    echo "Please install Docker Compose first."
    exit 1
fi

# Determine docker compose command
if docker compose version &> /dev/null; then
    DOCKER_COMPOSE="docker compose"
else
    DOCKER_COMPOSE="docker-compose"
fi

echo -e "${GREEN}Docker and Docker Compose are installed.${NC}"
echo ""

# Get installation details
echo -e "${YELLOW}Please provide the following information:${NC}"
echo ""

# Instance name
read -p "Instance name (e.g., bertram, powercode) [wallboard]: " INSTANCE_NAME
INSTANCE_NAME=${INSTANCE_NAME:-wallboard}
INSTANCE_NAME=$(echo "$INSTANCE_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

# Company name
read -p "Company name (displayed on dashboard) [Call Center]: " COMPANY_NAME
COMPANY_NAME=${COMPANY_NAME:-Call Center}

# Port
read -p "Web port [8080]: " APP_PORT
APP_PORT=${APP_PORT:-8080}

# Timezone
read -p "Timezone [America/Chicago]: " TIMEZONE
TIMEZONE=${TIMEZONE:-America/Chicago}

# Database passwords
echo ""
echo -e "${YELLOW}Database Configuration:${NC}"
DB_PASS=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
DB_ROOT_PASS=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)

read -p "Database password [auto-generated]: " INPUT_DB_PASS
DB_PASS=${INPUT_DB_PASS:-$DB_PASS}

read -p "Database root password [auto-generated]: " INPUT_ROOT_PASS
DB_ROOT_PASS=${INPUT_ROOT_PASS:-$DB_ROOT_PASS}

# AMI Configuration
echo ""
echo -e "${YELLOW}AMI Configuration (can also be set later in Admin GUI):${NC}"
read -p "AMI Host (e.g., pbx.example.com): " AMI_HOST
read -p "AMI Port [5038]: " AMI_PORT
AMI_PORT=${AMI_PORT:-5038}
read -p "AMI Username: " AMI_USER
read -sp "AMI Password: " AMI_PASS
echo ""

# Admin user
echo ""
echo -e "${YELLOW}Admin User:${NC}"
read -p "Admin username [admin]: " ADMIN_USER
ADMIN_USER=${ADMIN_USER:-admin}
read -sp "Admin password: " ADMIN_PASS
echo ""

if [ -z "$ADMIN_PASS" ]; then
    ADMIN_PASS=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c 12)
    echo -e "${YELLOW}Generated admin password: ${GREEN}$ADMIN_PASS${NC}"
fi

# Confirm
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}Installation Summary:${NC}"
echo -e "  Instance Name: ${GREEN}$INSTANCE_NAME${NC}"
echo -e "  Company Name:  ${GREEN}$COMPANY_NAME${NC}"
echo -e "  Web Port:      ${GREEN}$APP_PORT${NC}"
echo -e "  Timezone:      ${GREEN}$TIMEZONE${NC}"
echo -e "  AMI Host:      ${GREEN}${AMI_HOST:-Not configured}${NC}"
echo -e "  Admin User:    ${GREEN}$ADMIN_USER${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

read -p "Continue with installation? [Y/n]: " CONFIRM
if [[ "$CONFIRM" =~ ^[Nn] ]]; then
    echo "Installation cancelled."
    exit 0
fi

# Create installation directory
INSTALL_DIR="/opt/wallboard/$INSTANCE_NAME"
echo ""
echo -e "${YELLOW}Creating installation directory: $INSTALL_DIR${NC}"
sudo mkdir -p "$INSTALL_DIR"
sudo cp -r . "$INSTALL_DIR/"
cd "$INSTALL_DIR"

# Create .env file
echo -e "${YELLOW}Creating configuration file...${NC}"
cat > docker/.env << EOF
# Instance Configuration
INSTANCE_NAME=$INSTANCE_NAME
APP_PORT=$APP_PORT

# Database Configuration
DB_NAME=wallboard
DB_USER=wallboard
DB_PASS=$DB_PASS
DB_ROOT_PASS=$DB_ROOT_PASS
DB_PORT=3306

# Timezone
TIMEZONE=$TIMEZONE
EOF

# Create config.php
echo -e "${YELLOW}Creating application config...${NC}"
mkdir -p src/config
cat > src/config/config.php << EOF
<?php
/**
 * Application Configuration
 * Generated by installer on $(date)
 */

// Database (loaded from environment in Docker)
define('DB_HOST', getenv('DB_HOST') ?: 'localhost');
define('DB_PORT', getenv('DB_PORT') ?: '3306');
define('DB_NAME', getenv('DB_NAME') ?: 'wallboard');
define('DB_USER', getenv('DB_USER') ?: 'wallboard');
define('DB_PASS', getenv('DB_PASS') ?: '');

// Application
define('APP_NAME', 'Wallboard');
define('APP_VERSION', '1.0.0');
define('INSTANCE_NAME', '$INSTANCE_NAME');
EOF

# Create logs directory
mkdir -p logs
chmod 777 logs

# Build and start containers
echo ""
echo -e "${YELLOW}Building and starting Docker containers...${NC}"
cd docker
$DOCKER_COMPOSE up -d --build

# Wait for database to be ready
echo -e "${YELLOW}Waiting for database to be ready...${NC}"
sleep 10

# Insert initial configuration
echo -e "${YELLOW}Configuring initial settings...${NC}"

# Wait a bit more for MySQL to be fully ready
sleep 5

# Insert AMI config if provided
if [ -n "$AMI_HOST" ] && [ -n "$AMI_USER" ]; then
    $DOCKER_COMPOSE exec -T db mysql -u root -p"$DB_ROOT_PASS" wallboard << EOF
INSERT INTO ami_config (ami_host, ami_port, ami_username, ami_password, is_active)
VALUES ('$AMI_HOST', $AMI_PORT, '$AMI_USER', '$AMI_PASS', 1);
EOF
fi

# Update company name
$DOCKER_COMPOSE exec -T db mysql -u root -p"$DB_ROOT_PASS" wallboard << EOF
UPDATE company_config SET company_name = '$COMPANY_NAME', timezone = '$TIMEZONE';
EOF

# Create admin user
ADMIN_HASH=$(php -r "echo password_hash('$ADMIN_PASS', PASSWORD_DEFAULT);")
$DOCKER_COMPOSE exec -T db mysql -u root -p"$DB_ROOT_PASS" wallboard << EOF
INSERT INTO users (username, password_hash, role, is_active)
VALUES ('$ADMIN_USER', '$ADMIN_HASH', 'admin', 1);
EOF

# Done!
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                            ║${NC}"
echo -e "${GREEN}║          Installation Complete!                            ║${NC}"
echo -e "${GREEN}║                                                            ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "Wallboard URL:    ${BLUE}http://localhost:$APP_PORT${NC}"
echo -e "Admin Panel:      ${BLUE}http://localhost:$APP_PORT/admin${NC}"
echo -e "Admin Username:   ${GREEN}$ADMIN_USER${NC}"
echo -e "Admin Password:   ${GREEN}$ADMIN_PASS${NC}"
echo ""
echo -e "Installation directory: ${YELLOW}$INSTALL_DIR${NC}"
echo ""
echo -e "${YELLOW}Useful commands:${NC}"
echo "  cd $INSTALL_DIR/docker"
echo "  $DOCKER_COMPOSE logs -f        # View logs"
echo "  $DOCKER_COMPOSE restart        # Restart services"
echo "  $DOCKER_COMPOSE stop           # Stop services"
echo "  $DOCKER_COMPOSE start          # Start services"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Configure your AMI settings in Admin Panel (if not done during install)"
echo "  2. Add your queues in Admin Panel > Queues"
echo "  3. Add your extensions in Admin Panel > Extensions"
echo "  4. Open the wallboard URL to view your dashboard"
echo ""
