<?php
/**
 * Alert Sender - Delivers notifications via email, Slack, Teams webhooks
 *
 * @package VitalPBX-Asterisk-Wallboard
 */

class AlertSender {
    private $db;
    private $smtpConfig = null;

    public function __construct($db) {
        $this->db = $db;
        $this->loadSmtpConfig();
    }

    private function loadSmtpConfig() {
        $stmt = $this->db->query("SELECT * FROM smtp_config WHERE is_configured = 1 LIMIT 1");
        $this->smtpConfig = $stmt->fetch(PDO::FETCH_ASSOC);
    }

    /**
     * Send alert via all configured methods
     */
    public function sendAll($rule, $data) {
        $sentTo = [];
        $sentVia = [];

        // Send emails
        if ($this->smtpConfig) {
            $emailRecipients = $this->sendEmails($rule, $data);
            if (!empty($emailRecipients)) {
                $sentTo = array_merge($sentTo, $emailRecipients);
                $sentVia[] = 'email';
            }
        }

        // Send to Slack
        if ($this->sendSlackWebhooks($rule, $data)) {
            $sentVia[] = 'slack';
        }

        // Send to Teams
        if ($this->sendTeamsWebhooks($rule, $data)) {
            $sentVia[] = 'teams';
        }

        // Update alert_history with delivery info
        if (!empty($sentVia)) {
            $stmt = $this->db->prepare("
                UPDATE alert_history
                SET sent_to = ?, sent_via = ?
                WHERE alert_type = ?
                ORDER BY sent_at DESC LIMIT 1
            ");
            $stmt->execute([
                implode(', ', $sentTo),
                implode(',', $sentVia),
                $rule['alert_type']
            ]);
        }

        return !empty($sentVia);
    }

    private function sendEmails($rule, $data) {
        $recipients = [];

        // Get active email recipients
        $stmt = $this->db->query("
            SELECT * FROM alert_recipients
            WHERE is_active = 1 AND receives_email = 1 AND email IS NOT NULL AND email != ''
        ");

        while ($recipient = $stmt->fetch(PDO::FETCH_ASSOC)) {
            $sent = $this->sendEmail(
                $recipient['email'],
                $this->buildEmailSubject($rule, $data),
                $this->buildEmailBody($rule, $data)
            );

            if ($sent) {
                $recipients[] = $recipient['email'];
            }
        }

        return $recipients;
    }

    private function buildEmailSubject($rule, $data) {
        $severity = strtoupper($rule['severity'] ?? 'ALERT');
        return sprintf("[%s] %s - Wallboard Alert", $severity, $rule['alert_name']);
    }

    private function buildEmailBody($rule, $data) {
        $timestamp = date('Y-m-d H:i:s');
        $severityColor = ($rule['severity'] ?? 'warning') === 'critical' ? '#dc3545' : '#ffc107';

        return <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body style="font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5;">
    <div style="max-width: 600px; margin: 0 auto; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
        <div style="background: {$severityColor}; padding: 20px; color: #fff;">
            <h2 style="margin: 0;">⚠️ {$rule['alert_name']}</h2>
        </div>

        <div style="padding: 20px;">
            <p style="font-size: 18px; color: #333; margin: 0 0 20px 0;">
                {$data['message']}
            </p>

            <table style="border-collapse: collapse; width: 100%;">
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #eee; color: #666;"><strong>Alert Type:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #eee;">{$rule['alert_type']}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #eee; color: #666;"><strong>Threshold:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #eee;">{$rule['threshold']} {$rule['threshold_unit']}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #eee; color: #666;"><strong>Current Value:</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #eee;">{$data['current_value']}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; color: #666;"><strong>Time:</strong></td>
                    <td style="padding: 10px;">{$timestamp}</td>
                </tr>
            </table>
        </div>

        <div style="padding: 15px 20px; background: #f9f9f9; border-top: 1px solid #eee; font-size: 12px; color: #999;">
            This alert was generated by VitalPBX Wallboard
        </div>
    </div>
</body>
</html>
HTML;
    }

    private function sendEmail($to, $subject, $htmlBody) {
        if (!$this->smtpConfig) {
            return false;
        }

        $smtp = $this->smtpConfig;

        try {
            $headers = [
                'MIME-Version: 1.0',
                'Content-type: text/html; charset=utf-8',
                'From: ' . ($smtp['from_name'] ?? 'Wallboard') . ' <' . $smtp['from_address'] . '>',
                'Reply-To: ' . $smtp['from_address'],
                'X-Mailer: PHP/' . phpversion()
            ];

            $result = @mail($to, $subject, $htmlBody, implode("\r\n", $headers));
            $this->log("Email to $to: " . ($result ? 'sent' : 'failed'));
            return $result;

        } catch (Exception $e) {
            $this->log("Email error to $to: " . $e->getMessage());
            return false;
        }
    }

    private function sendSlackWebhooks($rule, $data) {
        $sent = false;
        $stmt = $this->db->query("
            SELECT * FROM webhook_config
            WHERE webhook_type = 'slack' AND is_active = 1
        ");

        while ($webhook = $stmt->fetch(PDO::FETCH_ASSOC)) {
            if ($this->sendSlack($webhook['webhook_url'], $rule, $data)) {
                $sent = true;
            }
        }

        return $sent;
    }

    private function sendSlack($url, $rule, $data) {
        $severity = $rule['severity'] ?? 'warning';
        $color = $severity === 'critical' ? '#dc3545' : '#ffc107';
        $emoji = $severity === 'critical' ? ':rotating_light:' : ':warning:';

        $payload = [
            'attachments' => [[
                'color' => $color,
                'blocks' => [
                    [
                        'type' => 'header',
                        'text' => [
                            'type' => 'plain_text',
                            'text' => $emoji . ' ' . $rule['alert_name'],
                            'emoji' => true
                        ]
                    ],
                    [
                        'type' => 'section',
                        'text' => [
                            'type' => 'mrkdwn',
                            'text' => '*' . $data['message'] . '*'
                        ]
                    ],
                    [
                        'type' => 'context',
                        'elements' => [
                            [
                                'type' => 'mrkdwn',
                                'text' => ':clock1: ' . date('g:i A') . ' | Threshold: ' . $rule['threshold'] . ' ' . $rule['threshold_unit']
                            ]
                        ]
                    ]
                ]
            ]]
        ];

        return $this->postWebhook($url, $payload);
    }

    private function sendTeamsWebhooks($rule, $data) {
        $sent = false;
        $stmt = $this->db->query("
            SELECT * FROM webhook_config
            WHERE webhook_type = 'teams' AND is_active = 1
        ");

        while ($webhook = $stmt->fetch(PDO::FETCH_ASSOC)) {
            if ($this->sendTeams($webhook['webhook_url'], $rule, $data)) {
                $sent = true;
            }
        }

        return $sent;
    }

    private function sendTeams($url, $rule, $data) {
        $severity = $rule['severity'] ?? 'warning';
        $color = $severity === 'critical' ? 'FF0000' : 'FFA500';

        $payload = [
            '@type' => 'MessageCard',
            '@context' => 'http://schema.org/extensions',
            'themeColor' => $color,
            'summary' => $rule['alert_name'],
            'sections' => [[
                'activityTitle' => '⚠️ ' . $rule['alert_name'],
                'activitySubtitle' => date('Y-m-d H:i:s'),
                'facts' => [
                    ['name' => 'Message', 'value' => $data['message']],
                    ['name' => 'Threshold', 'value' => $rule['threshold'] . ' ' . $rule['threshold_unit']],
                    ['name' => 'Current Value', 'value' => (string)$data['current_value']]
                ],
                'markdown' => true
            ]]
        ];

        return $this->postWebhook($url, $payload);
    }

    private function postWebhook($url, $payload) {
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
        curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 10);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);

        $result = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error = curl_error($ch);
        curl_close($ch);

        if ($httpCode >= 200 && $httpCode < 300) {
            $this->log("Webhook sent successfully to $url");
            return true;
        }

        $this->log("Webhook error ($httpCode) to $url: $error - $result");
        return false;
    }

    private function log($message) {
        $timestamp = date('Y-m-d H:i:s');
        $logFile = '/var/log/wallboard/alerts.log';
        @file_put_contents($logFile, "[$timestamp] [AlertSender] $message\n", FILE_APPEND);
    }
}
