<?php
/**
 * Application Configuration
 * Generated by installer on Mon Jan 19 06:19:29 PM UTC 2026
 */

// Database (loaded from environment in Docker)
define('DB_HOST', getenv('DB_HOST') ?: 'localhost');
define('DB_PORT', getenv('DB_PORT') ?: '3306');
define('DB_NAME', getenv('DB_NAME') ?: 'wallboard');
define('DB_USER', getenv('DB_USER') ?: 'wallboard');
define('DB_PASS', getenv('DB_PASS') ?: '');

// Application
define('APP_NAME', 'Wallboard');
define('APP_VERSION', '1.0.0');
define('INSTANCE_NAME', 'bertram-communications');
